//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakonaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_materials
    {
        public int order_material_id { get; set; }
        public int order_id { get; set; }
        public int material_id { get; set; }
        public decimal quantity_kg { get; set; }
        public decimal total_price { get; set; }
    
        public virtual materials materials { get; set; }
        public virtual orders orders { get; set; }
    }
}
