//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakonaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.order_materials = new HashSet<order_materials>();
            this.production_stages = new HashSet<production_stages>();
        }
    
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public int product_id { get; set; }
        public int manager_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public System.DateTime required_date { get; set; }
        public Nullable<System.DateTime> production_start_date { get; set; }
        public Nullable<System.DateTime> production_end_date { get; set; }
        public int quantity { get; set; }
        public decimal weight_kg { get; set; }
        public decimal price_per_ton { get; set; }
        public Nullable<decimal> weight_total { get; set; }
        public Nullable<decimal> total_cost { get; set; }
        public string status { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual customers customers { get; set; }
        public virtual employees employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_materials> order_materials { get; set; }
        public virtual products products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<production_stages> production_stages { get; set; }
    }
}
