//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakonaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.orders = new HashSet<orders>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int type_id { get; set; }
        public decimal length_m { get; set; }
        public Nullable<decimal> width_m { get; set; }
        public Nullable<decimal> height_m { get; set; }
        public decimal weight_kg { get; set; }
        public decimal price_per_ton { get; set; }
        public int standard_days { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orders> orders { get; set; }
        public virtual product_types product_types { get; set; }
    }
}
