//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakonaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class production_stages
    {
        public int stage_id { get; set; }
        public int order_id { get; set; }
        public string stage_name { get; set; }
        public System.DateTime planned_start_date { get; set; }
        public System.DateTime planned_end_date { get; set; }
        public Nullable<System.DateTime> actual_start_date { get; set; }
        public Nullable<System.DateTime> actual_end_date { get; set; }
        public Nullable<int> assigned_employee_id { get; set; }
        public string status { get; set; }
        public string notes { get; set; }
    
        public virtual employees employees { get; set; }
        public virtual orders orders { get; set; }
    }
}
